---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Weighted Quantile Sum (WQS) Permutation Test

<!-- badges: start -->
<!-- badges: end -->

The goal of wqsperm is to implement the weighted quantile sum (WQS) permutation test method. 

Weighted quantile sum regression is a statistical technique to evaluate the effect of complex exposure mixtures on an outcome (Carrico et al. 2015). It is a single-index method which estimates a combined mixture sum effect as well as weights determining each individual mixture component's contributions to the sum effect. However, the model features a statistical power and Type I error (i.e., false positive) rate tradeoff, as there is a machine learning step to determine the weights that optimize the linear model fit. If the full data is used to estimate both the mixture component weights and the regression coefficients, there is high power but also a high false positive rate since coefficient p-values are calculated for a weighted mixture independent variable calculated using weights that have already been optimized to find a large effect. 

We recently proposed an alternative method based on a permutation test that should reliably allow for both high power and low false positive rate when utilizing the WQSr. The permutation test is a method of obtaining a p-value by simulating the null distribution through permutations of the data. The permutation test algorithm is described more in detail in (reference Drew's paper).

## Installation

You can install the development version of wqsperm from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("jpspeng/wqsperm")
```

## Usage

Here is a [brief tutorial vignette](http://htmlpreview.github.io/?https://github.com/jpspeng/wqsperm/blob/working/vignettes/introduction.html) on how to use the wqsperm package.  
